name: release

on:
  push:
    branches:
      - "main"

permissions:
    contents: write
    packages: write


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          fetch-depth: "0"
      - name: Use Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      #TODO: Implement QA once tests are available
      - name: Run QA
        if: false
        run: |
          make qa
      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@2.7.1
      - name: Create new version
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          git tag v${{steps.get_next_version.outputs.version}}
          git push origin v${{steps.get_next_version.outputs.version}}
      - name: Build artifacts
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          make build BUILD_VERSION=${{ steps.get_next_version.outputs.version }}
      - name: Release new version
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          tag: v${{ steps.get_next_version.outputs.version }}
          generateReleaseNotes: true
